baseURL = 'https://docs.slapbirdapm.com'
languageCode = 'en-us'
title = 'SlapbirdAPM Docs'
theme = ['hugo-book']

[menu]
[[menu.before]]
  name = "SlapbirdAPM"
  url = "https://slapbirdapm.com"
  weight = 0

[params]
BookSection = '*'
